server:
  port: 9090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mysecretkeymysecretkeymysecretkey1234567890mysecretkey		
user:
  message: Hello from configuration server
app:
  environment: DEFAULT
